# 1. docker-compose build
# 2. docker-compose run web rake db:create db:migrate kandan:bootstrap
# 3. docker-compose up
---
version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
  web:
    build: .
    command: rails server thin -p 3000 -e development
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app

