# Postgres settings
# #################
local:
  adapter: postgresql
  username: postgres
  database: kandan_local
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  adapter: postgresql
  username: postgres
  host: db
  database: kandan_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 5
  timeout: 5000

#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
